name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t iulianbuzdugan/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true iulianbuzdugan/react-test npm test

      - run: docker build -t iulianbuzdugan/multi-client-hga ./client
      - run: docker build -t iulianbuzdugan/multi-nginx-hga ./nginx
      - run: docker build -t iulianbuzdugan/multi-server-hga ./server
      - run: docker build -t iulianbuzdugan/multi-worker-hga ./worker

      - run: docker push iulianbuzdugan/multi-client-hga
      - run: docker push iulianbuzdugan/multi-nginx-hga
      - run: docker push iulianbuzdugan/multi-server-hga
      - run: docker push iulianbuzdugan/multi-worker-hga

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: MultiDocker-env
          version_label: ${{ github.sha }}
          region: eu-central-1
          deployment_package: deploy.zip
